# =============================================================== CONFIGURATION FILE: FOR THE USER OT ENTER THE PARAMETERS OF THE SIMULATION =============================================================================================================================================================================================
# ===========================================================================================================================================================================================================================================================================================================================
# MANDATORY PARAMETERS

# --- Input files ---
input_shp_filename: "joined_layer_small_zone.shp" # name of the input shapefile located in the data/input/Shapefile folder 
crs: "EPSG:2154"   # CSR of the GIS project # crs: "EPSG:2056"  
input_flow_timeseries_filename: "April_September_2019_delta_one_hour.csv" # name of the flow time-series input file located in the data/input/Flow_data folder. 
time_step_min: 60.0   # timestep of the flow time-series in minutes (float, e.g., 10.0 for a 10 minute timestep)

# shapefile column configuration: the prefix of the columns containing the relevant information (e.g., for discharge 12.5 m3/s: "ho12_5" for the columns water depth and "vit12_5" for the water velocity)
shp_depth_prefix: "ho"
shp_vel_prefix: "vit"
shp_x_colname: "x_l93"
shp_y_colname: "y_l93"
shp_id_colname: "id"
shp_surf_colname: "surf_m2"

# ===============================================================
# --- Habitat classification thresholds ---
depth_threshold: 0.01   # minimum water depth (in meters) to consider a mesh wet (float, e.g., 0.01 for 1 cm, meaning that meshes will be considered wet if water depth is greater than 1 cm)

habitat_velocity_thresholds: # example of habitat classification thresholds based on current velocity and water depth (see user guide)
  # habitat type number 0 if dry conditions (water depth < depth_threshold)
  class_1: 0.05 # habitat type number 1 if v < 0.05 m/s
  class_2: 0.25 # habitat type number 2 if 0.05 ≤ v < 0.25 m/s
  class_3: 0.75 # habitat type number 3 if 0.25 ≤ v < 0.75 m/s
  class_4: 1.5 # habitat type number 4 if 0.75 ≤ v < 1.5 m/s
  class_5: 2.5 # habitat type number 5 if 1.5 ≤ v < 2.5 m/s
  # habitat type number 6 if v ≥ class_5 m/s
number_of_habitats: 7 # Integer : the number of habitats that you have based on this habitat classification (e.g., 7 for the previous classification: from 0 = dry to 6 = v ≥ class_5 m/s)

# ===============================================================
# --- Metrics calculation ---
target_habitat: # target habitat type for which the metrics will be calculated. Metrics are only calculated for the meshes that experience this habitat type at least once during the habitat time-series
  - 2 # unique integer from the habitat classification definition

metrics_to_compute: # metrics selection : "true" to compute the metric, "false" otherwise
  # Shifts
  shift_all_daily: true # daily shifts between all types of habitats
  shift_targ_daily: true # daily shifts between the suitable_hab_shifts habitat types
  shift_dry_daily: true # daily shifts to dry conditions

  # Desiccation
  dry_max: true # maximum consecutive time steps of dry conditions (in number of timesteps)
  desiccation_risk: true # associated desiccation risk value (see user manual)

  # Drift
  drift_percentile: true # drift percentile risk (see user manual)
  drift_max: true # associated maximum drift value (see user manual)
  drift_durations: true # number of timesteps spent is each drift category (in number of timesteps)

# --- Associated parameters ---
# Shifts
suitable_hab_shifts: [1, 2, 3, 4, 5] # list of habitat types considered “suitable” in between which shifts will be calculated --> shift_targ_daily

# Desiccation
start_at_first_occurrence: true # "true" to start the desiccation metric calculation after the first occurrence of the habitat type in the habitat time series. "false" to start the desiccation metric calculation at the beginning of the time-series 

desiccation_thresholds: # Example of desiccation thresholds based on consecutive durations spent outside of water (in hours)
  desicc_1: 1 #risk = 1 if dry consecutive time ≤ desicc_1
  desicc_2: 5 #risk = 2 if desicc_1 < dry consecutive time ≤ desicc_2
  desicc_3: 9 #risk = 3 if desicc_2 < dry consecutive time ≤ desicc_3
  # risk is 4 if dry consecutive time > desicc_3

# Drift
up_ramp: true # "true": drift_thresholds_with_ramp selected for drift calculation. "false", drift_thresholds selected (no consideration of ramp rate)

drift_thresholds_with_ramp: # Example of drift thresholds based on current velocity thresholds in m/s, if up_ramp is true (see user guide)
  drift_1: 0.4
  drift_2: 0.7
  drift_3: 1.0
  drift_ramp_threshold: 1.0   # cm/min

drift_thresholds: # Example of drift thresholds based on current velocity thresholds in m/s, without consideration of ramp rateif up_ramp is false (see user guide)
  drift_1: 1.2
  drift_2: 2.1
  drift_3: 3.0

# ===========================================================================================================================================================================================================================================================================================================================
# OPTIONAL: ADVANCED PARAMETERS
focus_on_zone: true # "true" if focus set on a specific zone (e.g., gravel bancs for eggs desiccation), "false" otherwise (by default)
zone_interest_filename: "banc_de_galet_v13feb2026.shp" # name of the focus zone shapefile located in the data/input/Focus_zone folder 
id_polygon_zone_interest: "ID_POLYGON" # shapefile's id column name of the polygons of interest (e.g., individual gravel bar id) /!\ This column needs to be named differently than the shp_id_colname id in the input shapefile. Rename the column if needed.
zone_ponte_field: "banc_galet" # name to give to this focus zone in output files (value of 1 if mesh part of the focus zone, 0 if not)
# what is expected to change if focus_on_zone is true: 
# - habitat attribution method is different and to be defnied by the user (see example function attribute_habitat_types_zone_only in habitat_attribution.py: habitat type -1 if not in focus zone, 0 if dry, 1 if wet but water depth or current velocity conditions for ovipositionare not met, 2 if suitable for egg desposition)
# - metrics are calculated only for the meshes that experience the target habitat type and are part of the focus zone (e.g., egg deposition suitable meshes of gravel bars) and not for the whole zone
# - shift_targ_daily metric calculates shifts to the target habitat type (and not between suitable_hab_shifts habitat types)
# - more statistics are calculated regarding the target habitat type and the dry conditions, and can serve as a source of inspiration for other types of focus zones and associated metrics
# - more plots are available in the optional outputs

# ===========================================================================================================================================================================================================================================================================================================================
# OPTIONAL: OUTPUT FILES PATHS FOR PLOTS AND/OR CLUSTERING
final_csv_path: "C:/Users/lecrivau/source/repos/HaDy_MZB/data/output/Long_small/Metric_files/metrics_Long_small.csv" # path to the output csv file containing the metrics values
final_shp_path: "C:/Users/lecrivau/source/repos/HaDy_MZB/data/output/Long_small/Metric_files/metrics_Long_small.shp" # path to the output shapefile containing the metrics values
static_habitat_csv_path: "C:/Users/lecrivau/source/repos/HaDy_MZB/data/output/Long_small/Habitat_classification/habitat_classification.csv" # path to the csv file containing the habitat classification of each mesh