name: Venv_HaDy_MZB
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - matplotlib
  - scikit-learn
  - numpy
  - geopandas
  - seaborn
  - scipy
  - pyyaml
  - pip:
    - scikit-posthocs